name: Deploy to website
on:
  workflow_run:
    workflows: ["CI"]
    #branches: [master]
    types:
      - completed
      - requested
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy artifacts to server and rebuild app
      run: |
        echo This is TODO
